services:
  php:
    build:
      context: ./
    command: php -S 0.0.0.0:80 -t public
    ports:
      - 80:80
    #volumes:
    #- /usr/src/myapp/vendor
    #- ./:/usr/src/myapp
    user: "${PHP_USER}:root"
    env_file:
      - .env
  #zipkin:
  #  image: openzipkin/zipkin-slim
  #  ports:
  #  - 9411:9411
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
    - 9412:9412
    - 16686:16686
  collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml